spring.application.name=noteshare-notes
server.port=8082

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.security.user.name=disabled
spring.security.user.password=disabled

jwt.secret=${JWT_SECRET}
jwt.expiration.ms=${JWT_EXPIRATION_MS}
